Script Updated

diff --git a/anime-terminal b/anime-terminal
--- a/anime-terminal
+++ b/anime-terminal
@@ -1,9 +1,9 @@
 #!/bin/sh
-player_fn="celluloid"
 
+player_fn="mpv"
 prog="anime-terminal"
 logfile="${XDG_CACHE_HOME:-$HOME/.cache}/ani-hsts"
-base_url="https://www2.gogoanime.cm//"
+base_url=$(curl -s -L -o /dev/null -w "%{url_effective}\n" https://gogoanime.cm)
 
 c_red="\033[1;31m"
 c_green="\033[1;32m"
@@ -18,12 +18,20 @@ help_text () {
 		printf "%s\n" "$line"
 	done <<-EOF
 	USAGE: $prog <query>
-	 -h		show this help text
-	 -d <query> 	download episode/s
-	 -H 		select unfinished anime & continue where you left off
-	 -H <query> 	continue where you left off
+	 -u	 shows anime from history with unwatched episodes
+	 -n	 show recent anime
+	 -h	 show this help text
+	 -d	 download episode
+	 -H	 continue where you left off
+	 -D	 delete history
+	 -q	 set video quality (best/worst/360/480/720/..)
+	 -k	 on keypress navigation (previous/next/replay/quit episode)
+	 -v	 use VLC as the media player
+	 h 	 to play episodes like '6.5' i.e, use 'h6'
+	 --dub	 play the dub version if present
 	EOF
 }
+
 
 die () {
 	printf "$c_red%s$c_reset\n" "$*" >&2
@@ -32,6 +40,22 @@ die () {
 
 err () {
 	printf "$c_red%s$c_reset\n" "$*" >&2
+}
+
+search_new () {
+	# get anime name along with its id
+
+	curl -s "$base_url" |
+	sed -n -E '
+		s_^[[:space:]]*<a href="/([^"/.]*)" title="([^"]*)".*_\1_p
+		' |
+	sed -n -E '
+		s_^[[:space:]]*([^"]*)-episode-[0-9]{1,100}*_\1_p
+		'
+}
+
+resolve_url () {
+	curl --silent --location --head --output /dev/null --write-out '%{url_effective}' -- $1
 }
 
 search_anime () {
@@ -65,7 +89,9 @@ get_embedded_video_link() {
 	anime_id=$1
 	ep_no=$2
 
-	curl -s "$base_url/$anime_id-episode-$ep_no" |
+	# credits to fork: https://github.com/Dink4n/ani-cli for the fix
+	# dub prefix takes the value "-dub" when dub is needed else is empty
+	curl -s "$base_url/$anime_id${dub_prefix}-episode-$ep_no" |
 	sed -n -E '
 		/^[[:space:]]*<a href="#" rel="100"/{
 		s/.*data-video="([^"]*)".*/https:\1/p
@@ -73,15 +99,33 @@ get_embedded_video_link() {
 		}'
 }
 
+
 get_links () {
-	embedded_video_url="$1"
-	curl -s "$embedded_video_url" |
-	sed -n -E '
-		/^[[:space:]]*sources:/{
-		s/.*(https[^'\'']*).*/\1/p
-		q
-		}
-		'
+	embedded_video_url=$(get_embedded_video_link "$anime_id" "$episode")
+	episode_id=$(echo "$embedded_video_url" | grep -oE "id.+?&")
+	video_url="https://gogoplay1.com/download?${episode_id}"
+}
+
+
+get_video_quality() {
+	
+	get_links
+	video_quality=$(curl -s get_links "$video_url" | grep -oE "(http|https):\/\/.*com\/cdn.*expiry=[0-9]*"| sort -V | sed 's/amp;//')
+	case $quality in
+		best)
+			play_link=$(echo "$video_quality" | sort -V | tail -n 1);;
+		worst)
+			play_link=$(echo "$video_quality" | sort -V | head -n 1);;
+        	*)
+  	             	play_link=$(echo "$video_quality" | grep -oE "(http|https):\/\/.*com\/cdn.*"${quality}".*expiry=[0-9]*")
+                	if [ -z "$play_link" ]; then
+                		printf "$c_red%s$c_reset\n" "Current video quality is not available (defaulting to highest quality)" >&2
+                		quality=best
+                		play_link=$(echo "$video_quality" | sort -V | tail -n 1)
+                	fi
+                	;;
+	esac
+	
 }
 
 dep_ch () {
@@ -105,8 +149,7 @@ get_search_query () {
 # create history file
 [ -f "$logfile" ] || : > "$logfile"
 
-#Anime selection
-
+# Anime selection
 anime_selection () {
 	search_results=$*
 	menu_format_string='[%d] %s\n'
@@ -153,48 +196,95 @@ anime_selection () {
 	EOF
 }
 
+search_for_unwatched () {
+	search_results=$*
+
+	unwatched_anime=""
+	while read anime_id; do
+		current_ep_number="$(search_eps "$anime_id")"
+		history_ep_number="$(sed -n -E "s/${anime_id}\t//p" "$logfile")"
+		if [ "$current_ep_number" -ge "$history_ep_number" ]
+		then
+			unwatched_anime="$unwatched_anime$anime_id\n"
+		fi
+	done <<-EOF
+	$search_results
+	EOF
+	[ -z $unwatched_anime ] && die "No unwatched episodes"
+	printf "%s""$unwatched_anime"
+}
+
 ## Ep selection
-
 episode_selection () {
-	[ $is_download -eq 1 ] &&
-		printf "Range of episodes can be specified: start_number end_number\n"
+	ep_choice_start="1"
+	if [ $last_ep_number -gt 1 ]
+	then
+		[ $is_download -eq 1 ] &&
+			printf "Range of episodes can be specified: start_number end_number\n"
 
-	printf "${c_blue}Choose episode $c_cyan[1-%d]$c_reset:$c_green " $last_ep_number
-	read ep_choice_start ep_choice_end
-	printf "$c_reset"
+		printf "${c_blue}Choose episode $c_cyan[1-%d]$c_reset$c_green: " $last_ep_number
+		read ep_choice_start ep_choice_end
+		if [ "$(echo "$ep_choice_start" | awk '{ printf substr($0, 1, 1) }')" = "h" ]
+		then
+			half_ep=1
+			ep_choice_start=$(echo "$ep_choice_start" | awk '{ printf substr($0, 2) }')
+		fi
+		printf "$c_reset"
+	fi
+}
 
+check_input() {
+	[ "$ep_choice_start" -eq "$ep_choice_start" ] 2>/dev/null || die "Invalid number entered"
+	episodes=$ep_choice_start
+	if [ -n "$ep_choice_end" ]; then
+		[ "$ep_choice_end" -eq "$ep_choice_end" ] 2>/dev/null || die "Invalid number entered"
+		# create list of episodes to download/watch
+		episodes=$(seq $ep_choice_start $ep_choice_end)
+	fi
+}
+
+append_history () {
+	grep -q -w "${selection_id}" "$logfile" ||
+		printf "%s\t%d\n" "$selection_id" $((episode+1)) >> "$logfile"
+}
+
+open_selection() {
+	for ep in $episodes
+	do
+		open_episode "$selection_id" "$ep"
+	done
+	episode=${ep_choice_end:-$ep_choice_start}
 }
 
 open_episode () {
 	anime_id=$1
 	episode=$2
-
 	# Cool way of clearing screen
-	printf '\x1B[2J\x1B[1;1H'
-	if [ $episode -lt 1 ] || [ $episode -gt $last_ep_number ]; then
+	tput reset
+	while [ "$episode" -lt 1 ] || [ "$episode" -gt "$last_ep_number" ]
+	do
 		err "Episode out of range"
 		printf "${c_blue}Choose episode $c_cyan[1-%d]$c_reset:$c_green " $last_ep_number
 		read episode
 		printf "$c_reset"
+	done
+
+	if [ $half_ep -eq 1 ]
+	then
+		temp_ep=$episode
+		episode=$episode"-5"
 	fi
 
-	printf "Getting data for episode %d\n" $episode
+	printf "Getting data for episode %s\n" $episode
+	
+	get_video_quality
+	status_code=$(curl -s -I get_video_quality "$play_link" | head -n 1|cut -d ' ' -f2)
 
-	embedded_video_url=$(get_embedded_video_link "$anime_id" "$episode")
-	video_url=$(get_links "$embedded_video_url")
-
-	case $video_url in
-		*streamtape*)
-			# If direct download not available then scrape streamtape.com
-			BROWSER=${BROWSER:-firefox}
-			printf "scraping streamtape.com\n"
-			video_url=$(curl -s "$video_url" | sed -n -E '
-				/^<script>document/{
-				s/^[^"]*"([^"]*)" \+ '\''([^'\'']*).*/https:\1\2\&dl=1/p
-				q
-				}
-			');;
-	esac
+	if [ $half_ep -eq 1 ]
+	then
+		episode=$temp_ep
+		half_ep=0
+	fi	
 
 	if [ $is_download -eq 0 ]; then
 		# write anime and episode number
@@ -202,33 +292,58 @@ open_episode () {
 			s/^${selection_id}\t[0-9]+/${selection_id}\t$((episode+1))/
 		" "$logfile" > "${logfile}.new" && mv "${logfile}.new" "$logfile"
 
-		setsid -f $player_fn --mpv-http-header-fields="Referer: $embedded_video_url" "$video_url" >/dev/null 2>&1
+		case $player_fn in
+
+			"mpv")
+				if echo "$status_code" | grep -vE "^2.*"; then
+					printf "${c_red}\nCannot reach servers!"
+				else
+					nohup $player_fn "$play_link" > /dev/null 2>&1 &
+					printf "${c_green}\nVideo playing"
+				fi;;
+			"vlc")
+				
+				if echo "$status_code" | grep -vE "^2.*"; then	
+					printf "${c_red}\nCannot reach servers!"
+				else
+					nohup $player_fn "$play_link" > /dev/null 2>&1 &
+					printf "${c_green}\nVideo playing"
+				fi;;
+		esac
 	else
 		printf "Downloading episode $episode ...\n"
 		printf "%s\n" "$video_url"
 		# add 0 padding to the episode name
 		episode=$(printf "%03d" $episode)
 		{
-			ffmpeg -headers "Referer: $embedded_video_url" -i "$video_url" \
-				-c copy "${anime_id}-${episode}.mkv" >/dev/null 2>&1 &&
+			ffmpeg -i "$play_link" -c copy "${anime_id}-${episode}.mkv" >/dev/null 2>&1 &&
 				printf "${c_green}Downloaded episode: %s${c_reset}\n" "$episode" ||
-				printf "${c_red}Download failed episode: %s${c_reset}\n" "$episode"
+				printf "${c_red}Download failed episode: %s , please retry or check your internet connection${c_reset}\n" "$episode"
 		}
 	fi
 }
 
-# Start Up
-
+# Start Up #
 # to clear the colors when exited using SIGINT
 trap "printf '$c_reset'" INT HUP
 
-dep_ch "$player_fn" "curl" "sed" "grep"
-
 # option parsing
 is_download=0
+half_ep=0
+quality=best
 scrape=query
-while getopts 'hdH' OPT; do
+navigation_type=0
+# navigation_type 0 - confirm selection by pressing enter
+# navigation_type 1 - no enter confirmation for selections
+
+while getopts 'knuhdHDq:-:v' OPT; do
 	case $OPT in
+		u)
+			scrape=history_new
+			;;
+		n)
+			scrape=new
+			;;
 		h)
 			help_text
 			exit 0
@@ -239,12 +354,34 @@ while getopts 'hdH' OPT; do
 		H)
 			scrape=history
 			;;
+
+		D)
+			: > "$logfile"
+			exit 0
+			;;
+		q)
+			quality=$OPTARG
+			;;
+    k)
+			navigation_type=1
+      ;;
+		-)
+			case $OPTARG in
+				dub)
+					dub_prefix="-dub"
+					;;
+			esac
+			;;
+		v)
+			player_fn="vlc"
+			;;
 	esac
 done
+
+dep_ch "$player_fn" "curl" "sed" "grep"
 shift $((OPTIND - 1))
 
-# main #
-
+# main
 case $scrape in
 	query)
 		get_search_query "$*"
@@ -259,39 +396,58 @@ case $scrape in
 		anime_selection "$search_results"
 		ep_choice_start=$(sed -n -E "s/${selection_id}\t//p" "$logfile")
 		;;
+	new)
+		search_results=$(search_new)
+		# echo "$search_results"
+		anime_selection "$search_results"
+		episode_selection
+		;;
+	history_new)
+		search_results=$(sed -n -E 's/\t[0-9]*//p' "$logfile")
+		[ -z "$search_results" ] && die "History is empty"
+		search_results=$(search_for_unwatched "$search_results")
+		anime_selection "$search_results"
+		ep_choice_start=$(sed -n -E "s/${selection_id}\t//p" "$logfile")
+		;;
 esac
 
-
-{ # checking input
-	[ "$ep_choice_start" -eq "$ep_choice_start" ] 2>/dev/null || die "Invalid number entered"
-	episodes=$ep_choice_start
-
-	if [ -n "$ep_choice_end" ]; then
-		[ "$ep_choice_end" -eq "$ep_choice_end" ] 2>/dev/null || die "Invalid number entered"
-		# create list of episodes to download/watch
-		episodes=$(seq $ep_choice_start $ep_choice_end)
-	fi
-}
-
-# add anime to history file
-grep -q -w "${selection_id}" "$logfile" ||
-	printf "%s\t%d\n" "$selection_id" $((episode+1)) >> "$logfile"
-
-for ep in $episodes
-do
-	open_episode "$selection_id" "$ep"
-done
-episode=${ep_choice_end:-$ep_choice_start}
+check_input
+append_history
+open_selection
 
 while :; do
 	printf "\n${c_green}Currently playing %s episode ${c_cyan}%d/%d\n" "$selection_id" $episode $last_ep_number
-	printf "$c_blue[${c_cyan}%s$c_blue] $c_yellow%s$c_reset\n" "n" "next episode"
-	printf "$c_blue[${c_cyan}%s$c_blue] $c_magenta%s$c_reset\n" "p" "previous episode"
-	printf "$c_blue[${c_cyan}%s$c_blue] $c_yellow%s$c_reset\n" "s" "select episode"
+	if [ "$episode" -ne "$last_ep_number" ]; then
+		printf "$c_blue[${c_cyan}%s$c_blue] $c_yellow%s$c_reset\n" "n" "next episode"
+	fi
+	if [ "$episode" -ne "1" ]; then
+		printf "$c_blue[${c_cyan}%s$c_blue] $c_magenta%s$c_reset\n" "p" "previous episode"
+	fi
+	if [ "$last_ep_number" -ne "1" ]; then
+		printf "$c_blue[${c_cyan}%s$c_blue] $c_yellow%s$c_reset\n" "s" "select episode"
+	fi
 	printf "$c_blue[${c_cyan}%s$c_blue] $c_magenta%s$c_reset\n" "r" "replay current episode"
+	printf "$c_blue[${c_cyan}%s$c_blue] $c_yellow%s$c_reset\n" "a" "search for another anime"
+	printf "$c_blue[${c_cyan}%s$c_blue] $c_magenta%s$c_reset\n" "h" "search history"
 	printf "$c_blue[${c_cyan}%s$c_blue] $c_red%s$c_reset\n" "q" "exit"
 	printf "${c_blue}Enter choice:${c_green} "
-	read choice
+
+	case "${navigation_type}" in
+		0)
+			read choice
+			;;
+		1)
+			stty_original="$(stty -g)"
+			stty cbreak
+			choice="$(dd bs=1 count=1 2> /dev/null)"
+			stty "${stty_original}"
+			;;
+		*)
+			die "navigation_type is invalid"
+			;;
+
+	esac
+
 	printf "$c_reset"
 	case $choice in
 		n)
@@ -303,6 +459,11 @@ while :; do
 
 		s)	printf "${c_blue}Choose episode $c_cyan[1-%d]$c_reset:$c_green " $last_ep_number
 			read episode
+			if [ "$(echo "$episode" | cut -c1-1)" = "h" ]
+			then
+				half_ep=1
+				episode=$(echo "$episode" | cut -c2-)
+			fi
 			printf "$c_reset"
 			[ "$episode" -eq "$episode" ] 2>/dev/null || die "Invalid number entered"
 			;;
@@ -310,8 +471,31 @@ while :; do
 		r)
 			episode=$((episode))
 			;;
+		a)
+			tput reset
+			get_search_query ""
+			search_results=$(search_anime "$query")
+			[ -z "$search_results" ] && die "No search results found"
+			anime_selection "$search_results"
+			episode_selection
+			check_input
+			append_history
+			open_selection
+			continue
+			;;
+		h)
+			tput reset
+			search_results=$(sed -n -E 's/\t[0-9]*//p' "$logfile")
+			[ -z "$search_results" ] && die "History is empty"
+			anime_selection "$search_results"
+			ep_choice_start=$(sed -n -E "s/${selection_id}\t//p" "$logfile")
+			check_input
+			append_history
+			open_selection
+			continue
+			;;
 
-		q)
+		q)	
 			break;;
 
 		*)
